# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.IntegerField()),
                ('DESCRICAO', models.CharField(max_length=255)),
                ('REFERENCIA', models.CharField(max_length=355)),
            ],
        ),
    ]
