# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meds',
            name='REFERENCIA',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='id',
        ),
        migrations.AlterField(
            model_name='meds',
            name='CODIGO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
